In [1]:
import os
import glob
import pandas as pd
import numpy as np

In [2]:
path_to_mean = r'C:\Niloofar\SCR\posture-prediction-models-main\data\mean-std_20_4_2025'

In [3]:
mean_data = pd.read_csv(os.path.join(path_to_mean, 'mean.csv'), header=None)
std_data = pd.read_csv(os.path.join(path_to_mean, 'std.csv'), header=None)

In [4]:
mean_data

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,25.048935,138.930410,-7.625518,110.426039,28.071054,-14.804786,33.957610,16.555004,89.881083,-17.604755,...,-147.742835,-100.632922,-137.256736,173.246872,164.564364,184.590010,153.023261,100.632922,151.917907,3.849226
1,292.599017,236.420737,223.794685,170.623015,122.767205,15.342562,206.472043,208.044323,20.759309,11.054647,...,53.828719,-0.764076,204.932806,101.134677,117.145535,86.614228,44.804669,0.764076,202.366833,2.881545
2,1448.083019,1447.174918,1488.049573,1484.605075,1376.562750,1120.288673,1273.479999,1115.757959,1254.158950,1078.700219,...,50.415142,39.013414,22.432938,757.884327,494.201528,338.399939,56.141996,40.465859,22.571790,8.443467

In [5]:
Means = pd.concat(101*[mean_data], axis=0)
Means.reset_index(inplace=True, drop=True)

Stds = pd.concat(101*[std_data], axis=0)
Stds.reset_index(inplace=True, drop=True)

In [6]:
f_means = [210.18638340655707, 289.51228353291765, 779.1597626742252]
f_stds = [317.8268718114922, 229.63004567188818, 564.7016492256631]
w_mean = 73.7
w_std = 9.83031026977277
h_mean = 177.8
h_std = 4.072468538859448

In [9]:

os.mkdir(r"C:\Niloofar\SCR\posture-prediction-models-main\external_data_processing\\converted_data\\Final_data")

for i in range(1):
    load_path = r"C:\Niloofar\SCR\posture-prediction-models-main\external_data_processing\converted_data\s1_filtered"
    save_path = r"C:\Niloofar\SCR\posture-prediction-models-main\external_data_processing\\converted_data\\Final_data\\s1"
    os.mkdir(save_path)
    all_files = glob.glob(load_path + "\*.csv")

    # should not imposing the effect of the test_subject in calculation fo mu and sigma for training
    for filename in all_files:
        df = pd.read_csv(filename, header=None)
        # df = pd.read_csv(r'D:\\Master\\term2\\Social Robotics\\Project\\code\\s1_filtered\\s1_1_f.csv', header=None)
        # df.columns = list(range(42))
        df_normal = (df.iloc[:, :41]-Means.iloc[:, :41])/Stds.iloc[:, :41]
        df = pd.concat([df_normal, df.iloc[:, 41]], axis=1)
        df.iloc[5, -1] = (df.iloc[5, -1] - w_mean) / w_std  # weight normalization
        df.iloc[6, -1] = (df.iloc[6, -1] - h_mean) / h_std  # height normalization
        df.iloc[0, -1] = (df.iloc[0, -1] - f_means[0]) / f_stds[0]
        df.iloc[1, -1] = (df.iloc[1, -1] - f_means[1]) / f_stds[1]
        df.iloc[2, -1] = (df.iloc[2, -1] - f_means[2]) / f_stds[2]
        df.to_csv(save_path+'\\'+filename.split('\\')[-1].split('.')[0]+'n'+'.csv', sep=',', index=False, header=None)

In [10]:
dfs = []
for i in range(1):
    path = r"C:\Niloofar\SCR\posture-prediction-models-main\external_data_processing\converted_data\s1_filtered"
    all_files = glob.glob(path + "\*.csv")
    
    for filename in all_files:
        df = pd.read_csv(filename, header=None)
        dfs.append(df)
        
combined_df = pd.concat(dfs, ignore_index=True)
combined_df

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,-79.627550,83.109349,-87.628074,55.791315,-18.678727,-27.490661,-10.187403,-4.274330,72.107580,-23.220711,...,-144.579841,-112.921328,-108.894568,178.253507,153.302864,160.816168,118.153780,67.652202,115.341055,-81.189906
1,130.423736,95.903206,3.151119,-21.487739,-33.660094,-59.949301,95.120351,167.836313,-110.769808,-44.358237,...,36.659107,-23.032524,171.312750,106.225912,40.786015,19.182037,10.508913,-36.774449,147.544182,533.376675
2,1591.906578,1580.478037,1583.312796,1577.646826,1442.904089,1094.847313,1357.072679,1209.746159,1247.423773,1062.168291,...,53.966669,47.066557,28.856701,736.919722,460.307880,360.588604,63.164685,48.550605,25.265695,285.808884
3,-79.735870,84.527094,-87.553240,55.865991,-18.142272,-27.391634,-10.221467,-4.361462,72.187104,-23.211849,...,-144.643574,-112.933348,-108.891490,178.054543,153.444704,160.869012,118.123537,67.638950,115.320854,1.000000
4,131.092997,98.297375,3.779779,-20.714802,-34.157896,-60.139921,95.593904,168.052335,-110.498835,-44.316979,...,36.641775,-23.045402,171.285469,106.019274,40.690998,18.944085,10.534243,-36.780695,147.543865,2.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9691,187.873746,19.911975,164.465826,18.784101,71.988986,-4.294242,79.711615,62.595960,-66.810638,-25.109463,...,-14.385161,-110.322197,111.322193,-92.663919,35.063255,19.629234,-56.004978,-78.139872,76.602049,0.000000
9692,876.305122,886.921151,949.235914,959.862830,906.409046,875.656162,739.587897,639.014512,877.565324,851.832788,...,52.889809,3.328054,28.489589,551.866203,411.078199,332.489287,62.036304,47.663561,25.503069,0.000000
9693,380.415139,401.557009,277.080916,299.038955,224.426142,-92.493363,202.752705,67.156332,116.750751,-127.705511,...,-133.273058,-99.575493,-89.922614,13.832991,158.045536,168.174392,88.613894,17.070291,125.747728,0.000000
9694,186.732484,18.791338,163.382010,17.700136,71.153276,-4.541412,79.175898,62.281334,-67.345398,-25.354562,...,-14.418531,-110.352358,111.273452,-92.896227,35.274813,19.758671,-56.070224,-78.128293,76.562087,0.000000
9695,873.699607,884.118740,946.487836,956.993476,903.538419,873.441204,736.824531,636.490214,874.966255,849.699947,...,52.827355,3.320729,28.469165,550.399072,410.797735,332.480049,62.027105,47.568293,25.516329,0.000000

In [11]:
new_df = combined_df.iloc[:, 0:41].to_numpy()
new_df = new_df.reshape(-1, 41*3)
pd_df = pd.DataFrame(new_df)
pd_df

,0,1,2,3,4,5,6,7,8,9,...,113,114,115,116,117,118,119,120,121,122
0,-79.627550,83.109349,-87.628074,55.791315,-18.678727,-27.490661,-10.187403,-4.274330,72.107580,-23.220711,...,194.265228,53.966669,47.066557,28.856701,736.919722,460.307880,360.588604,63.164685,48.550605,25.265695
1,-79.735870,84.527094,-87.553240,55.865991,-18.142272,-27.391634,-10.221467,-4.361462,72.187104,-23.211849,...,194.263421,54.003216,47.050768,28.858925,736.929717,460.328498,360.619725,63.155510,48.552032,25.281226
2,-79.822461,85.759661,-87.480324,55.937368,-17.661283,-27.314516,-10.245948,-4.430231,72.262882,-23.209508,...,194.264822,54.034852,47.037318,28.859990,736.934785,460.341464,360.644768,63.144080,48.555159,25.293503
3,-79.871749,86.665928,-87.412160,56.002213,-17.277516,-27.273285,-10.252070,-4.465609,72.333703,-23.216879,...,194.271067,54.058429,47.028508,28.858530,736.931410,460.341255,360.659527,63.129167,48.560955,25.300148
4,-79.876175,87.184217,-87.352134,56.057495,-17.011560,-27.270429,-10.233915,-4.459827,72.399475,-23.233087,...,194.281533,54.073277,47.026126,28.853220,736.918680,460.325857,360.662172,63.110937,48.569286,25.300186
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3227,379.472829,401.394326,276.244477,298.891544,224.150497,-93.411719,203.343789,69.034759,116.414734,-128.257799,...,146.049229,53.001393,3.345329,28.510267,557.199711,412.265264,332.786836,62.047892,48.078941,25.477843
3228,379.866014,401.659955,276.662592,299.186627,224.436342,-92.997687,203.339661,68.670465,116.616722,-127.970365,...,145.747773,52.986484,3.340389,28.513689,555.239441,411.795128,332.624975,62.041823,47.911330,25.483152
3229,380.143568,401.751625,276.926943,299.284645,224.556753,-92.726468,203.227336,68.223604,116.733064,-127.800371,...,145.480613,52.945984,3.334653,28.505960,553.464448,411.401755,332.529688,62.040186,47.773921,25.491552
3230,380.319513,401.699415,277.055073,299.215842,224.540483,-92.571760,203.017826,67.700183,116.774419,-127.725073,...,145.243574,52.889809,3.328054,28.489589,551.866203,411.078199,332.489287,62.036304,47.663561,25.503069
3231,380.415139,401.557009,277.080916,299.038955,224.426142,-92.493363,202.752705,67.156332,116.750751,-127.705511,...,145.029403,52.827355,3.320729,28.469165,550.399072,410.797735,332.480049,62.027105,47.568293,25.516329

In [12]:
max_m = pd_df.max()
max_m

0      540.346209
1      553.406187
2      486.971225
3      511.749134
4      419.734056
          ...
118    463.235730
119    370.142336
120     68.268424
121     58.961829
122     26.466996
Length: 123, dtype: float64

In [13]:
min_m = pd_df.min()
min_m

0     -232.925178
1      -64.420215
2     -204.182905
3      -61.320611
4      -96.858302
          ...
118    332.768191
119    263.935111
120     59.020853
121     39.169107
122     24.570939
Length: 123, dtype: float64

In [14]:
dif = max_m - min_m
dif

0      773.271388
1      617.826401
2      691.154130
3      573.069745
4      516.592358
          ...
118    130.467539
119    106.207225
120      9.247571
121     19.792723
122      1.896058
Length: 123, dtype: float64

In [15]:
pd_df.isnull().sum().sum()

0

In [16]:
dif = dif.to_numpy()
dif = dif.reshape(-1, 41)
dif = pd.DataFrame(dif)
dif

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,773.271388,617.826401,691.154130,573.069745,516.592358,236.401514,419.741858,234.378101,339.428992,206.793203,...,41.355745,38.407053,42.838193,41.073379,193.920445,124.743037,98.710587,45.326312,56.428709,57.927730
1,504.708330,587.557368,597.025185,648.575776,568.197445,341.180495,399.710204,196.879527,524.226916,320.151669,...,163.479219,110.647077,107.528780,107.907924,258.455934,196.958015,179.112339,107.128577,106.041200,108.097985
2,874.306292,861.450195,759.297232,755.404155,633.803037,451.366220,688.049157,665.720351,520.532595,448.113444,...,57.207944,7.367376,55.283477,2.367828,320.004887,130.467539,106.207225,9.247571,19.792723,1.896058

In [18]:
dif.to_csv(r'C:\Niloofar\SCR\posture-prediction-models-main\external_data_processing\converted_data\s1_filtered\dif.csv' ,index=False, header=None)